
@baseUrl = http://localhost
@port = 5423
@apiPrefix = api/v1

### HEALTH ROUTES
GET {{baseUrl}}:{{port}}/health/check

### USER ROUTES
###
GET {{baseUrl}}:{{port}}/users
###
GET {{baseUrl}}:{{port}}/users/235262
###
PUT {{baseUrl}}:{{port}}/users/edit/203948
###
PATCH {{baseUrl}}:{{port}}/users/edit/203948
###
POST {{baseUrl}}:{{port}}/users/register
###
POST {{baseUrl}}:{{port}}/users/remove
###
POST {{baseUrl}}:{{port}}/users/register
Content-Type: application/json

{
	"username": "uzaneim",
	"email": "uza@neim.com",
	"password": "7815696ecbf1c96e6894b779456d330e",
}


### AUTH
###
POST {{baseUrl}}:{{port}}/auth/login
Content-Type: application/json

{
	"username": "uzaneim",
	"email": "uza@neim.com",
	"password": "7815696ecbf1c96e6894b779456d330e",
}
###
GET {{baseUrl}}:{{port}}/auth/logout

### 404
GET {{baseUrl}}:{{port}}/errror
