
@baseUrl = http://localhost
@port = 5423
@apiPrefix = api/v1

### endpoints


### get health check
GET {{baseUrl}}:{{port}}/health/check

### post user create
POST {{baseUrl}}:{{port}}/users/create
Content-Type: application/json

{
	"x": 1223,
	"y": 563,
	"k": "zanel"
}

### 404
GET {{baseUrl}}:{{port}}/errror
