version: '3.9'

services:
  api:
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/api:ro
      - /usr/api/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5423
    ports:
      - '5423:5423'
    command: npm run dev
