version: '3.9'

services:
  api:
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/api:ro
      - /usr/api/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5423
    ports:
      - '5423:5423'
    command: npm run dev

  database:
    image: mongo
    container_name: mongo_database_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

volumes:
  database:
